import { Navbar } from "../Navbar";
import Head from "next/head";
import styles from "./MainLayout.module.css"
import { PropsWithChildren } from "react";
import { ScriptProps } from "next/script";

export const MainLayout: React.FC<PropsWithChildren<ScriptProps>> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Diario de Vicente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>{children}</main>
    </div>
  );
};
